---
include:
  - board: nice_nano
    shield: settings_reset
  - board: nrfmicro_13
    shield: settings_reset

  # ---- Sofle ----
  # - board: nice_nano
  #   shield: sofle_dongle dongle_display_091_oled
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   artifact-name: sofle_dongle

  - board: nice_nano
  #   shield: sofle_left custom_nice_view_adapter custom_nice_view
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: sofle_central_left

  # - board: nice_nano
  #   shield: sofle_left custom_nice_view_adapter custom_nice_view
  #   cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  #   artifact-name: sofle_peripheral_left

  - board: nice_nano
  #   shield: sofle_right custom_nice_view_adapter custom_nice_view
    shield: sofle_right 
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_peripheral_right

  # ---- gbEnki ----
  - board: nice_nano
    shield: gbEnki_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: gbEnki_left

  - board: nice_nano
    shield: gbEnki_right
    artifact-name: gbEnki_right

  # ---- gbEnki dongle ----
  - board: nice_nano
    shield: gbEnki_dongle nice_view_adapter dongle_display_view_pro_micro
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: gbEnki_dongle

  - board: nice_nano
    shield: gbEnki_dongle_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: gbEnki_dongle_left

  - board: nice_nano
    shield: gbEnki_dongle_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: gbEnki_dongle_right

  # ---- Keyball ----
  - board: nrfmicro_13
    shield: keyball61_left
    artifact-name: keyball_left

  - board: nice_nano
    shield: keyball61_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: keyball_right
